name: Wake up Bot
on:
  schedule:
    # Esegue ogni 10 minuti, dalle 08:00 alle 23:00 circa (ora italiana)
    - cron: '*/10 6-21 * * *'
  workflow_dispatch: # <--- QUESTA RIGA SBLOCCA IL TASTO "RUN WORKFLOW"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl -s https://deepthought-4ywi.onrender.com > /dev/null